### ISSUE TITLE
Convert the Ant build to Grunt for the documentation

### ISSUE THREAD

**Issue by RubenOlsen** [jqPlot/jqPlot#1]
# Problem description

It makes much more sense to use Grunt to build the documentation, rather sticking with ant.

# Todo

Convert the current Ant build to Grunt.

# Done criteria for closing this issue

When the Grunt build produces the same output as the current ant build.

**Comment by johanbove** [comment]
Will we keep using NaturalDocs?

**Comment by RubenOlsen** [comment]
Aren't we doing the JSDoc stuff? This will in the future remove the need to use NaturalDocs. 

Ruben @ mobildings. Alle skrivefeil og korte svar skyldes autokorrektur.

**Comment by johanbove** [comment]
Well I did some initial tests on the current commenting and it works fine in NaturalDocs; Rewriting all the docs to JsDoc notation is going to take some work. Therefore I gave this issue the status "epic" since there's going to be a couple of steps to go through to migrate to JsDoc. If everyone is agreeing to that of course.

**Comment by ppritcha** [comment]
I agree that we should move from NaturalDocs to JSDoc.  It would be good to have an all-javascript toolchain for building jqPlot and the web pages for jqPlot.

**Comment by johanbove** [comment]
Closing this since the documentation is being built with Grunt.
