### ISSUE TITLE
Looking for a new owner / repository archival

### ISSUE THREAD

**Issue by johanbove** [jqPlot/jqPlot#171]
This project is looking for a new owner position due to not being able to fix current open issues and dealing with the pull requests.

Please reply here if you're interested in keeping the project from being [archived](https://help.github.com/articles/about-archiving-repositories/).

There are currently probably [better graphing libraries](https://duckduckgo.com/?q=javascript+graph+library+open+source&atb=v121-1__&ia=web) available for your JavaScript projects.

I would suggest the excellent [chartjs](https://www.chartjs.org/).

Thank you to all collaborators for helping out!

**Comment by rswestmoreland** [comment]
Hello,

I just emailed you but then saw you point out this issue to reply to, so I am replying here as well.

I would like to become the new owner if that is still an option.

Thanks,
Richard

**Comment by johanbove** [comment]
Hi @rswestmoreland , Thanks for offering your help. Why would you like to become the new owner of this project?

**Comment by johanbove** [comment]
In the meantime I've made you a member of the team, so you can start having a look around.

**Comment by rswestmoreland** [comment]
I started using Jqplot several years ago for a big reporting project and at
the time it was my favorite out of all the others I tested.  I know some
other newer chart libraries have come along, but, just as with most
opensource projects I know those too will eventually be replaced by the
next best thing.

I've recently had to work on another reporting project and as it turns out
these newer libraries don't play well with wkthmltopdf.  Fortunately jqplot
still works with it.  What I would like to do is keep Jqplot going as a
quality alternative to Chart.js, with emphasis on ensuring it renders
properly and quickly when used to produce a PDF.

Thanks,
Rick

**Comment by johanbove** [comment]
Thank you for making clear that there is still a need for jqPlot in 2018!

>  What I would like to do is keep Jqplot going as a quality alternative to Chart.js, with emphasis on ensuring it renders properly and quickly when used to produce a PDF.

This sounds like a good project where we can collect requirements and current issues that we need to deal with.
