### ISSUE TITLE
Chart with stackSeries=true cause legends click strike-line shift

### ISSUE THREAD

**Issue by harryzhux** [jqPlot/jqPlot#177]
![screenshot from 2018-10-10 11-50-04](https://user-images.githubusercontent.com/10911789/46759198-9822ce00-cc83-11e8-8ede-7dadbaa9d551.png)
![screenshot from 2018-10-10 11-50-19](https://user-images.githubusercontent.com/10911789/46759205-9fe27280-cc83-11e8-8340-d284531ccfc9.png)
For plot with non-stacked series, this is fine: clicked D (red), it removes the red line in the plot, and the legend item D got striking line indicating it is removed from the plot.

![screenshot from 2018-10-10 11-50-53](https://user-images.githubusercontent.com/10911789/46759369-197a6080-cc84-11e8-9a06-9a8123aa7ad6.png)
![screenshot from 2018-10-10 11-51-05](https://user-images.githubusercontent.com/10911789/46759376-1d0de780-cc84-11e8-9447-a3824c3b5ccf.png)
Notice that for this stacked series graph, clicked D, it removes the red line in the plot correctly, however, item A got striking line, which is wrong.

The following code can be used to reproduce the issue:
[stackseries-legends-bug.html.txt](https://github.com/jqPlot/jqPlot/files/2466096/stackseries-legends-bug.html.txt)

**Comment by dg-spark** [comment]
Thanks for raising this bug. The issue is related to the code which applies the hidden class, it does not handle the reversal of the legend and therefore applies the hidden class to the inverse index.

I recommend that the legend elements store the series idx so they can be identified correctly. 

I will create a fork for this change

**Comment by harryzhux** [comment]
Thanks for the quick response and fix. However, it seems introduced another bug when the legend set to have multiple columns, e.g. the plot below has 2 columns in the legend, click the first one make the striking line applied to both items in the same line; and click the second item did not have striking effects, although both remove the line in the plot correctly.
![screenshot from 2018-10-11 14-11-37](https://user-images.githubusercontent.com/10911789/46834581-a1ce3380-cd60-11e8-830b-5ef8620f4c6d.png)
![screenshot from 2018-10-11 14-11-57](https://user-images.githubusercontent.com/10911789/46834590-a5fa5100-cd60-11e8-807e-19de9bfe2edf.png)

**Comment by dg-spark** [comment]
Hi Harry,

Thanks for performing testing and identifying that issue. I have changed the code to apply series id to td(column) elements so other elements on the row are not striked.

Updated code for <enhancedLegendRenderer> is available on my fork: [Here](https://github.com/dg-spark/jqPlot/blob/issue-177-class/src/plugins/jqplot.enhancedLegendRenderer.js)

Please let me know if you have any issues. Otherwise I will create a merge request.

Daniel

**Comment by harryzhux** [comment]
Daniel,
Tested and verified, works great. Thank you!
